name: Build and Update calendars

on:
  schedule:
    - cron: 0 0/4 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare script for execution
        run: chmod a+x run.sh

      - name: Run build and update script
        run: ./run.sh

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
