name: Build and Update calendars in PRs

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare script for execution
        run: chmod a+x run.sh

      - name: Run build and update script
        run: ./run.sh

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
